version: '3.8'
services:
  app:
    build: .
    ports:
      - "8089:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/agenda_manager?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agenda_manager
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    # Backend Spring Boot
      backend:
        build: .  # Usa el Dockerfile del backend
        ports:
          - "8080:8080"
        depends_on:
          - db
        environment:
          SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/agendamanager
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root

      # Frontend Angular (opcional: si quieres dockerizar Angular)
      frontend:
        image: nginx:alpine
        ports:
          - "4200:80"
        volumes:
          - ./frontend/dist:/usr/share/nginx/html  # Ajusta la ruta a tu build de Angular
        depends_on:
          - backend
volumes:
  mysql_data: